---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-forgejo
spec:
  template:
    spec:
      containers:
        - name: opentofu
          env:
            - name: FORGEJO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: forgejo-admin-secret
                  key: username
            - name: FORGEJO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: forgejo-admin-secret
                  key: password
          image: oowy/opentofu:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir /work
              cd /work
              cp /config/forgejo.tf .
              tofu init
              tofu apply -auto-approve
          volumeMounts:
            - mountPath: /config
              name: forgejo-configuration
      restartPolicy: Never
      volumes:
        - name: forgejo-configuration
          configMap:
            name: forgejo-configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-configuration
data:
  forgejo.tf: |
    terraform {
      required_providers {
        forgejo = {
          source = "svalabs/forgejo"
        }
      }
    }

    provider "forgejo" {
      host     = "http://forgejo-http:3000"
    }

    resource "forgejo_repository" "clone" {
      name       = "openmetadata-dbt-demo"
      clone_addr = "https://github.com/stackabletech/openmetadata-dbt-demo.git"
      mirror     = false
    }