---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: stackable-airflow
type: Opaque
stringData:
  database: airflow
  password: airflow
  postgres-password: w70lpAuF73
  username: airflow
