---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-credentials
type: Opaque
stringData:
  adminUser.email: airflow@airflow.com
  adminUser.firstname: Airflow
  adminUser.lastname: Admin
  adminUser.password: adminadmin
  adminUser.username: admin
  connections.celeryBrokerUrl: redis://:airflow@redis-airflow-master:6379/0
  connections.celeryResultBackend: db+postgresql://airflow:airflow@postgresql-airflow/airflow
  connections.secretKey: airflowSecretKey
  connections.sqlalchemyDatabaseUri: postgresql+psycopg2://airflow:airflow@postgresql-airflow/airflow
