---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-minio-connection
spec:
  encryptedData:
    airflow-minio-connection: AgAyIKxLttsBudutuqh5gywSa9gE67qSqIQDMWo8DKM/ql5/HJiuwaS/ijgowUKC3bh4N6s5f82h/wG38qzFQf2Kpadi30w+5EywsNn7nhyCeOuiM6nrAZ5QjleeNPXo5RZIciVQEAmoejGPMAuGJaBP/Fxp+0TdLdQ2CHHmWyuvTxOpD3wyPEL5pb840HzJqsPLHC6BWb2qYVfdeAsjCMioLOlKcYZOO1Np4CdqDAS1cISjMk0DTU+ndQJoZIsnyyOjU0lg9APEdL58eqUhbtJeUM5NSDLNUr3dg6gDRc5NeW6A/omqStD7P9R0cL2Szl3g6MJvZ9XXjBfRE+tEgJvcJc21dzBhLN2jKwxZ6B8kVfRnyg1vzmOhoaGPn4AMhJe8brUK38zFa5BUCgiLJXraPebJZAoYKSBbfdSdeB23t0zfLas0NvhYtnjJtLnxa+SYkZlbVZpJEXNlMBGpOt3Ao1xsVX6Ky3ke53gXoutyRT/FYQvmbwnL3UpIZ+hixfFHPpC8E4QX8Ii37DiGr4ni4ybii3hjg5PoFnrRb+epQBZTWPuAs4PN9EJOoXasiBfdd31thLT0WrkVloj5KnrII0AWGbOskxgLL0KeOsGhDhEoRzyeIYkZ6Nr5vOnVBczrAJhlfJe6WNey1WTz8ICZ7d9f23YJJ9OYQJoAZcphNXbGa6uG8F+p7ZBmQ6Mc7AZdukZltiicqAPJdks9yyPb+zEZvT8TEK9Tf1SBRlAkUGssn9ZheuxcRYwRMnJ5t0ZHBHJQTJgRFaOk0m+bSSNVdCv4P5oyjT5fIrb+vzq2Omm68iT6t9cd
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-minio-connection
    type: Opaque
