---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-minio-connection
spec:
  encryptedData:
    airflow-minio-connection: AgAk7nueczxSliKQH2GNLE1vfyksldh5ZehCpvWJphMkSyOygdzXvIhje7d+qHnHktBCbc6uKolLlHZ/MTlJB6CmCxtpbRjnVXS9M4RXBAxPZROBsEbcmYrlv+WC4WDVBEVD2vyJFwmsMBal68TpplWoDFwhM1sCo/F5HZI2CVCcyNoIh3ExxQa0yvH94SIXFj1VrqNBwFr9gJwm+NpBoHW74e+PBq+2fVckueA8OH6e2FxEPIK1QIOtjW6qXD+bzktf1aHJ2sR+R1gMGP3ATibt0Usm7QOlrRQKmvqjI8SZGxwgJ6O6Z+OHEA62M/amUMIJmlYbc6sGbrL5Oe/W/xRZlGh7Vbbhb2jmbSgc5O2Fg9sAi6r8YfU5U8GnwYKJOpI3GecpasJVjuT7ZgwZpZnyjXqIndhmXKio3Lz/8pt4S189vk2pIXfIqLAjV2No96aehx1ZlJMdO8+m4AJLYxymP5y0yindZocoKjLAcicJaLeepBZmsGcq7N1ymAvz89zUSaIMHu1H6pa9l3nfmKLhhH53tknnBeJtjzQoIlJoYUQ1E72soEGli/GqHkdlzJ2/XdkFfOZ4dKYvv7X3mDeZXzLdT4bpg84uUIRzDeXJHl77rNr5+VNkv1mCv4hBRh8c+kLeC3C3zUh+PkFDf9AUa7k5v+I2cWvEEdLvG2R+U9xHrwiHv/1j28McUHpjNIXyazKX0vbI5sr/RPlETtP4TEdYyXf078WXpZEQ7WxHpc4PTQ0AY0XupoYGYYDOJ2UHsTsYgTrSL2dmYS8hoOTicbGWr62HJkxhigqn8DKxtmbt+EupU6i0
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-minio-connection
    type: Opaque
